/*
 * Copyright (c) 2025 MASSDRIVER EI (massdriver.space)
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_BL61X_CLOCK_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_BL61X_CLOCK_H_

#define BL61X_CLKID_CLK_ROOT		0
#define BL61X_CLKID_CLK_RC32M		1
#define BL61X_CLKID_CLK_CRYSTAL		2
#define BL61X_CLKID_CLK_WIFIPLL		3
#define BL61X_CLKID_CLK_AUPLL		4
#define BL61X_CLKID_CLK_BCLK		5

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_BFLB_BL61X_CLOCK_H_ */
